### ISSUE TITLE
Can't install on GHC 9

### ISSUE THREAD

**Issue by benjamin-hodgson** [EmaApps/ema#115]
When I try to add an `ema` dependency to a project built with GHC 9.0 or 9.2, it fails to compile. The error message says:

```
[10 of 11] Compiling Ema.App          ( src/Ema/App.hs, dist/build/Ema/App.o, dist/build/Ema/App.dyn_o )

src/Ema/App.hs:114:66: error:
    Ambiguous occurrence ‘lookupEnv’
    It could refer to
       either ‘Prelude.lookupEnv’,
              imported from ‘Prelude’ at src/Ema/App.hs:7:8-14
              (and originally defined in ‘Relude.Lifted.Env’)
           or ‘System.Environment.lookupEnv’,
              imported from ‘System.Environment’ at src/Ema/App.hs:27:28-36
    |
114 |       port <- liftIO $ fromMaybe 8000 . (readMaybe @Int =<<) <$> lookupEnv "PORT"
    |                                                                  ^^^^^^^^^
```

The dependencies in my cabal file look like this:

```
    build-depends:
        -- ghc 9.0; also fails on 9.2 with base 4.16
        base >= 4.15.0,
        ema
```

It looks like `ema`'s dependency on `relude 0.7` is getting overridden, because `relude 0.7` requires `base < 4.15`. Looking at the packages which actually got installed, it seems like Cabal went for `relude 1.1` - and the conflicting `lookupEnv` export was [added in `relude 1.0`](https://hackage.haskell.org/package/relude-1.1.0.0/docs/Relude-Lifted-Env.html#v:lookupEnv).

As a (prospective) user, I'd be happiest if you shrank `ema`'s dependency footprint and removed `relude` altogether (use the standard prelude instead), but of course that's your decision 😄

Thanks!

**Comment by srid** [comment]
@benjamin-hodgson The `multisite` branch (#81) fixes this, and almost rewrites Ema for better composability and new features (generic route encoding, etc.). See https://github.com/fpindia/fpindia-site for a real-world example. I'm also in the process of writing docs in that branch. It should be released by end of this month, but you can give it a try already by using either the fpindia repo or https://github.com/EmaApps/ema-template/pull/22

I made a note of your concern with the `relude` dependency.

**Comment by benjamin-hodgson** [comment]
Thanks! I'll look out for when the rewrite gets released 😄
