### ISSUE TITLE
Simplify complex compile errors when using generic deriving

### ISSUE THREAD

**Issue by srid** [EmaApps/ema#116]
Part of this is due to the use of `generics-sop`. And it happens when writing route types and deriving `IsRoute` generically (via `GenericRoute`). Accidental typos or mistyping can produce really gnarly compile errors.

For example, with this change:

```diff
--- a/src/Ema/Example/Ex03_Store.hs
+++ b/src/Ema/Example/Ex03_Store.hs
@@ -97,7 +97,7 @@ deriveGeneric ''ProductRoute
 deriveIsRoute
   ''ProductRoute
   [t|
-    '[ WithModel (Map Slug Product)
+    '[ WithModel ()
      , WithSubRoutes
         '[ FileRoute "index.html"
          , StringRoute Product Slug
```

we get this complex error from ghc:

<img width="581" alt="image" src="https://user-images.githubusercontent.com/3998/179303310-93866eeb-73b2-46f5-bb6c-8ad75320085c.png">

Or with this change:

```diff
diff --git a/src/Ema/Example/Ex03_Store.hs b/src/Ema/Example/Ex03_Store.hs
index 236fa72..80a0e8a 100644
--- a/src/Ema/Example/Ex03_Store.hs
+++ b/src/Ema/Example/Ex03_Store.hs
@@ -100,7 +100,6 @@ deriveIsRoute
     '[ WithModel (Map Slug Product)
      , WithSubRoutes
         '[ FileRoute "index.html"
-         , StringRoute Product Slug
          ]
      ]
     |]
```

we see ghc throwing:

<img width="579" alt="image" src="https://user-images.githubusercontent.com/3998/179303396-e0d97ae1-5a47-4b06-b213-2f81a13a2757.png">

These can really scare newcomers off.

**Comment by RiugaBachi** [comment]
So the major scenarios that I could think of to cover were:

1) ADT + WithSubRoutes shape mismatch
2) Incompatible constructor field + corresponding WithSubRoutes list index
4) ADT + WithSubModels shape mismatch
5) Incompatible constructor field + corresponding WithSubModels index
6) WithModel, after factoring into account WithSubModels specification if it exists, is incompatible with subroute models

Can you think of any other cases worth checking for?

**Comment by srid** [comment]
> Alternatively we can ignore case 5 since the type error isn't terribly bad I guess? 

Without all the context in mind - intuitively, this sounds good to me. We can always revisit this later.  But we can document case 5 in `docs/guide/route/generic/errors.md` (title: "Dealing with complex errors in generic deriving") for users?

> Can you think of any other cases worth checking for?

At the moment, no. If we come across any in the future, I think we can add it to `errors.md` as first step, and then see if it is possible to provide a friendly type error for it (thus removing its entry from `errors.md`).

**Comment by srid** [comment]
That PR is a great improvement. In [the fpindia-site](https://github.com/fpindia/fpindia-site) I just noticed that for the following:

<img width="492" alt="image" src="https://user-images.githubusercontent.com/3998/180024774-96cf4335-cc5e-43d6-b253-c4c11441f986.png">

I get:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/3998/180024798-27c52f13-4b79-4bf0-8e06-c5a2f31db302.png">

Which is not particular super useful. If the error message also showed the route constructor name, it would be more helpful to the user.

**Comment by srid** [comment]
@RiugaBachi Looks like I overlooked this. But am I correct in understanding that the downside of doing all of this is that when you derive `IsRoute` generically on the type itself (ie., not as standalone deriving) the error messages become even less useful? 

Specifically, I see:

<img width="640" alt="image" src="https://user-images.githubusercontent.com/3998/181041414-a68e8fd9-c236-42c2-8c2b-a6116103817e.png">

**Comment by srid** [comment]
The above kind of error happens for the following type:

```haskell
data CategoryRoute
  = CategoryRoute_Index
  | CategoryRoute_Category Slug
  deriving stock (Show, Eq, Ord, Generic)
  -- We can also do this using TemplateHaskell (see ProductRoute deriving below)
  deriving
    (IsRoute)
    via (GenericRoute CategoryRoute '[])
```

And if I add back the geneirc-sop deriving, ie.:

```haskell
data CategoryRoute
  = CategoryRoute_Index
  | CategoryRoute_Category Slug
  deriving stock (Show, Eq, Ord, Generic)
  -- We can also do this using TemplateHaskell (see ProductRoute deriving below)
  deriving anyclass (SOP.Generic, SOP.HasDatatypeInfo)
  deriving
    (IsRoute)
    via (GenericRoute CategoryRoute '[])
```

then I see:

<img width="513" alt="image" src="https://user-images.githubusercontent.com/3998/181043673-47112d91-1bf5-4d6a-b1a8-3e459b903749.png">

**Comment by RiugaBachi** [comment]
That's one of the regressions I fixed IIRC. Let me get around to pushing my fixes for #122 and then I'll get that PR up.

**Comment by srid** [comment]
@RiugaBachi Is there anything left to do for this? I'm close to releasing 0.8.

**Comment by RiugaBachi** [comment]
Yea i'll get around to making that regression fix PR.

**Comment by srid** [comment]
Another case,

https://github.com/EmaApps/ema/issues/131#issuecomment-1217370610
