### ISSUE TITLE
Decide between `Coercible` and `GIsomorphic`

### ISSUE THREAD

**Issue by srid** [EmaApps/ema#131]
Reported by @lucasvreis 
https://matrix.to/#/!ygGUISjbmnwJPtaUmH:matrix.org/$QiIKTbwnR7UfyfiIgESHGK1URYOtuQLvgsVkieTpDV8?via=matrix.org&via=hummingbard.com&via=t2bot.io

![image](https://user-images.githubusercontent.com/3998/184918066-0561ad8a-a527-406a-8871-d7f396d134e2.png)

Do this before 0.8. Which of these should we use?

**Comment by lucasvreis** [comment]
Another note: before my PR, I was also not getting the "pretty" error message that should be shown when the types were not "isomorphic", but an ugly one involving the `Rep` type:
![Captura de tela de 2022-08-16 22-57-34](https://user-images.githubusercontent.com/4229115/185017778-6a9333b6-f139-4fd9-9c12-ba0ab90b2ee4.png)
