### ISSUE TITLE
Live server redirects static assets to wrong links

### ISSUE THREAD

**Issue by lucasvreis** [EmaApps/ema#138]
**Describe the bug**
When clicking on anchor links that point to static files (`AssetStatic`) on the live server, the browser is redirected to the wrong address.

**To Reproduce**
1. Clone `ema-template`
3. Add a line like the following patch:
```patch
diff --git a/src/Main.hs b/src/Main.hs
index 314785f..3e7c022 100644
--- a/src/Main.hs
+++ b/src/Main.hs
@@ -80,6 +80,7 @@ renderBody :: Prism' FilePath Route -> Model -> HtmlRoute -> H.Html
 renderBody rp model r = do
   H.div ! A.class_ "container mx-auto mt-8 p-2" $ do
     renderNavbar rp r
+    H.a ! A.href (staticRouteUrl rp model "logo.svg") $ "Click me"
     H.h1 ! A.class_ "text-3xl font-bold" $ H.toHtml $ routeTitle r
     case r of
       HtmlRoute_Index -> do
```
3. Run the live server
5. Click on the new "Click me" link
6. Browser is redirected to `/static/logo.svg`
7. Get `decodeRoute returned Nothing` error

Note: the right `/logo.svg` path gets inserted into history, so pressing the back button makes the logo display as expected.
 
**Expected behavior**
Browser should be redirected to the `/logo.svg` link and logo displayed.

**Desktop (please complete the following information):**
 - Browser: Firefox, Chromium

**Additional context**
This is a bug related to the live server, since disabling JS on the browser fixes the issue. This also explains why like images, stylesheets and scripts get loaded without problems.

**Comment by srid** [comment]
> Note: the right `/logo.svg` path gets inserted into history, so pressing the back button makes the logo display as expected.

I find it weird that it goes back to the logo again; it should go back to the original route. That seems to be another bug. It happens even after #139

**Comment by lucasvreis** [comment]
> I find it weird that it goes back to the logo again; it should go back to the original route. That seems to be another bug. It happens even after #139
After the PR I see it behaving correctly in Firefox, and in Chrome too, but in Chrome the address is changed back to the original route while the page itself does not change. Is this what you see?
