### ISSUE TITLE
Upload haddocks to hackage

### ISSUE THREAD

**Issue by jhrcek** [EmaApps/ema#140]
Hello,

could you please upload documentation of ema 0.8.2.0 to hackage?
I was just going through https://ema.srid.ca/tutorial and wanted to browse through the api docs while following the tutorial, but unfortunately the docs are not generated on hackage: https://hackage.haskell.org/package/ema-0.8.2.0

**Comment by jhrcek** [comment]
Sorry, It seems 0.8.2.0 was released to hackage just today and docs build is pending. If that's the case, feel free to close this issue :smile:

**Comment by srid** [comment]
Yea try https://hackage.haskell.org/package/ema-0.8.0.0 meanwhile
